version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  Init-Build:
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12 #
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: featherr_test

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/featherr-engineering/rest-api

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Run Build
          command: |
            dep ensure
            go build -v
      - run:
          name: Run Tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./tests
  Deploy-Build:
    - run:
        name: Deploy Buid
        command: |
          echo 'Hello World!'
          echo 'This is the delivery pipeline'


worksflow:
  version: 2
  Build_WorkFlow:
    jobs:
      - Init-Build
      - Deploy-Build:
          requires:
            - Hold-For-Approval


