workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Init-Build
      - Now-Complete:
          type: approval



version: 2.0
jobs:
  Init-Build:
    docker:
      - image: circleci/golang:1.12
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: featherr_test

    working_directory: /go/src/github.com/featherr-engineering/rest-api

    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Run Build
          command: |
            dep ensure
            go build -v
      - run:
          name: Run Tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./tests
  Now-Complete:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'





